app:
  telegram:
    base_url: https://api.telegram.org/bot{token}/sendMessage
    message: |
      [ALERTA] - O sistema de alerta detectou chuva no escritÃ³rio do Antonio, 
      por favor fechem as janelas e portas ğŸŒ§ï¸ â˜”

